//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFEjercicio01.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public int Id_Sex { get; set; }
        public int Id_Country { get; set; }
        public int Id_Status { get; set; }
        public string DNI { get; set; }
        public Nullable<int> Age { get; set; }
        public string Workclass { get; set; }
        public Nullable<int> Fnlwgt { get; set; }
        public string Education { get; set; }
        public Nullable<int> Education_num { get; set; }
        public string Occupation { get; set; }
        public string Relationship { get; set; }
        public string Race { get; set; }
        public Nullable<int> Capital_gain { get; set; }
        public Nullable<int> Capital_loss { get; set; }
        public Nullable<int> Hours_per_week { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual Status Status { get; set; }
    }
}
